Fix 'TypeError: t.toFixed is not a function' error. Note, this might cause other problems that are currently hidden by this error; e.g. if the 'tofixed' Nunjucks filter is not the last one in a pipe.
Signed-off-by: Volker Theile <votdev@gmx.de>