Fix bug in netplan.io configuration for WiFi interfaces.
ERROR: wlx0014785193b8: networkd backend does not support wifi with match:, only by interface name
Signed-off-by: Volker Theile <votdev@gmx.de>
(cherry picked from commit 8fef89e2a0ffddef56ce099c18ca5e346298c266)