Hardening Salt state
... to prevent errors like:
```
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/net/eth0/addr_assign_type'
```

Signed-off-by: Volker Theile <votdev@gmx.de>
(cherry picked from commit 480bf1e910a4a92247d804d386389598ea6c3b79)
Signed-off-by: Volker Theile <votdev@gmx.de>