Execute omv-salt with LANG=C.UTF-8 to ensure it works and does not run into the Python click issue:
root@omv5box:/home/vagrant# omv-salt
Traceback (most recent call last):
  File "/usr/sbin/omv-salt", line 135, in <module>
    sys.exit(main())
  File "/usr/sbin/omv-salt", line 131, in main
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/usr/lib/python3/dist-packages/click/_unicodefun.py", line 119, in _verify_python3_env
    'mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

This system supports the C.UTF-8 locale which is recommended.
You might be able to resolve your issue by exporting the
following environment variables:

    export LC_ALL=C.UTF-8
    export LANG=C.UTF-8

Signed-off-by: Volker Theile <votdev@gmx.de>